Add Resources tab on the broker-details page
arkmq-org/activemq-artemis-self-provisioning-plugin pull request #18
Opened 2024-12-24 15:56 UTC by Msarawan

Added Resources tab on the broker-details page to list all the resources of the deployed broker.

![Screenshot from 2024-12-24 21-22-27](https://github.com/user-attachments/assets/9f9965d0-b69b-4bc4-a865-ffb0f57c97ce)

fixes: [#15](https://github.com/arkmq-org/activemq-artemis-self-provisioning-plugin/issues/15)

2025-01-02 10:20 UTC, lavocatt requested changes
That's a good first step. All the information is there, however there are styling differences between this view and the standard one:

![image](https://github.com/user-attachments/assets/b7710f0f-a57a-4064-8e28-65e959ea8c0b)

What I would like to see in this PR:

- [x] add the ability to sort on the columns
- [x] add the colored logos
- [ ] remove the check mark for the status
- [ ] sort by default on name alphabetically

2025-01-02 10:46 UTC, Msarawan commented
> That's a good first step. All the information is there, however there are styling differences between this view and the standard one:
> 
> ![image](https://private-user-images.githubusercontent.com/86971992/399673383-b7710f0f-a57a-4064-8e28-65e959ea8c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTM5ODgsIm5iZiI6MTczNTgxMzY4OCwicGF0aCI6Ii84Njk3MTk5Mi8zOTk2NzMzODMtYjc3MTBmMGYtYTU3YS00MDY0LThlMjgtNjVlOTU5ZWE4YzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDEwMjgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYzkxNzNhZGVkMDk0OWI3NDdlODU4YzhjYzIzMDM0MzhkMDdlMmFjYmVmN2EzMzYwMjAzYmQ5Y2MxYjBhZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QLGo9hc3SGs0DsNhsd6CbrHNdhW2djHnD-qZTqn9D8Q)
> 
> What I would like to see in this PR:
> 
> * [ ]  add the ability to sort on the columns
> * [ ]  add the colored logos
> * [ ]  remove the check mark for the status
> * [ ]  sort by default on name alphabetically

Hello @lavocatt , The green check mark icon on the status field is also present in the standard OLM view, so initially i thought of adding it to our custom resources view for consistency. But now, can we remove it, even though it’s added as a part of the standard olm view?
![Screenshot from 2025-01-02 15-57-45](https://github.com/user-attachments/assets/47958057-8597-4e24-98d9-897ef29c5ef1)

2025-01-02 10:49 UTC, lavocatt commented
> Hello @lavocatt , The green check mark icon on the status field is also present in the standard OLM view, so initially i thought of adding it to our custom resources view for consistency. But now, can we remove it, even though it’s added as a part of the standard olm view? 

Ah, it wasn't showing on mine, in that case, leave it there then.

2025-01-16 16:43 UTC, lavocatt approved these changes
This is a very good piece of work. Thanks for your efforts. :rocket:

2025-01-16 16:43 UTC, merged