Add yaml view tab on the Broker Deatails Page
arkmq-org/activemq-artemis-self-provisioning-plugin pull request #4
Opened 2024-12-12 07:35 UTC by Msarawan

2024-12-12 14:18 UTC, lavocatt commented
The navlinks are rendering a bit strangely I find, the CSS looks very washed out 
![image](https://github.com/user-attachments/assets/cacdcf29-94ee-4a62-a299-a54e59c989b0)

2024-12-12 14:24 UTC, lavocatt requested changes
I think we need to move to HorizontalNav from the dynamic plugin SDK, the patternfly horizontal nav renders not the same.

![image](https://github.com/user-attachments/assets/31736b9e-4763-4f72-a44b-8829f05b4a19)

2024-12-12 14:26 UTC, Msarawan commented
> The navlinks are rendering a bit strangely I find, the CSS looks very washed out ![image](https://private-user-images.githubusercontent.com/86971992/395196030-cacdcf29-94ee-4a62-a299-a54e59c989b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMTM1MjYsIm5iZiI6MTczNDAxMzIyNiwicGF0aCI6Ii84Njk3MTk5Mi8zOTUxOTYwMzAtY2FjZGNmMjktOTRlZS00YTYyLWEyOTktYTU0ZTU5Yzk4OWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDE0MjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YWZhYzdlYzBjN2M0YzBiNTNmYjJhZWRmYWZjZDVkYjg5M2E1OThkMDMzYTc0YmNmNTU0NjJhZmNmY2EwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oWubGLxHbd9suFDlqPMifoWA4JL0VpEoOownbmerBxs)

Yes, that is currently happening because of as we removed the patternfly Page and PageSection components and related css . so in the light-mode we are unable to see those navigation tab names....
but, as i always use my screen in dark mode i forgot to update that....i will fix that now..

2025-01-09 09:28 UTC, lavocatt reviewed
Very good progress on this, it's almost ready to get merged. The only mandatory part is to update the link text for the YAML readonly warning. I'll create a follow up issue for the other point I'm mentioning.

2025-01-09 09:28 UTC, lavocatt commented on src/brokers/broker-details/components/yaml/Yaml.container.tsx
> +        </Button>
I think we should change this text, I've seen in an internal document that the usage of "click here" is very outdated. I grew up in the 90s so it seems fine to me, but apparently it is not. What about we update the test to:
`Proceed to the edit form to apply changes` and only set the `edit form` part of the sentence as the link to get to the edit form. Would that work for you?

2025-01-09 09:28 UTC, lavocatt commented on src/brokers/broker-details/BrokerDetails.container.tsx
> +            loading={loadingBrokerCr}
I have a bit of an issue with the [prop drilling](https://react.dev/learn/passing-data-deeply-with-context#the-problem-with-passing-props) of the loading state. I would like us to handle the loading state very early in the life cycle of the component instead.

What I mean by that, is that we could early return a loading `"something"` when the CR is loading, as there is even no point in attempting to log to even try to render the page if we don't have data available. And I would also do the same if the CR returns an error.

So I would change the logic of the function below to something like:

```
export const BrokerDetailsPage: FC = () => {
  const { ns: namespace, name } = useParams<{ ns?: string; name?: string }>();

  const { brokerCr, isLoading, error } = useGetBrokerCR(name, namespace);
  
  if (isLoading) {
    return // A centered Bullseyed XL Spinner or something
  }
  if (error) {
    return // An error item
  }
  return (
    <>
      <JolokiaAuthentication brokerCR={brokerCr} podOrdinal={0}>
        <AuthenticatedPageContent
          brokerCr={brokerCr}
          name={name}
          namespace={namespace}
          loading={isLoading}
          error={error}
        />
      </JolokiaAuthentication>
    </>
  );
};
```
Then we can remove all these probs about the loading state and the error, which in turn would simplify our code & testing.

So since this should also be applied to the AddressPage, I think this could be a good follow-up issue. So I'm in favor of merging your PR without this one, but we should tackle this soon.

2025-01-09 09:30 UTC, lavocatt commented on src/brokers/broker-details/BrokerDetails.container.tsx
> +            loading={loadingBrokerCr}
Here's the issue for the followup https://github.com/arkmq-org/activemq-artemis-self-provisioning-plugin/issues/24

2025-01-09 16:31 UTC, merged